name: Deployment

# Only deploy on "main" branch pushes
on:
  push:
    branches: [ "main" ]

  # Enable manual runs if desired
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout a copy of the repository
      - name: Checkout
        uses: actions/checkout@v2.7.0

      # If you have dependencies to install, include these two steps.
      # Otherwise, you can omit them.
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: cd custom_functions && yarn && cd ..
      # End dependencies installation steps

      # Deploy the code to our HarperDB Instance
      - name: Deploy Custom Functions
        uses: makvoid/deploy-harperdb-cf-action@main
        with:
          admin_username: ${{ secrets.HDB_ADMIN_USERNAME }}
          admin_password: ${{ secrets.HDB_ADMIN_PASSWORD }}
          hdb_endpoint: ${{ vars.HDB_ENDPOINT }}
          project_name: ${{ vars.HDB_PROJECT }}
          cf_directory: 'custom_functions'
          reject_unauthorized_certs: 'false'
